#pragma once

#include "Colony Overview State.h"
#include "Colony Build Queue State.h"
#include "Colony View State.h"
#include "Encyclopedia State.h"
#include "Fleets Overview State.h"
#include "Galaxy View State.h"
#include "Leaders Overview State.h"
#include "Planet Overview State.h"
#include "Planetary Bombardment State.h"
#include "Planetary Combat State.h"
#include "Research State.h"
#include "Ship Design State.h"
#include "Ship Refit State.h"
#include "Space Combat State.h"
#include "System View State.h"
#include "New Game Setup State.h"
